// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebAPITest2.Models;

public partial class DBContext : DbContext
{
    public DBContext(DbContextOptions<DBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Branch> Branch { get; set; }

    public virtual DbSet<WebTeleNo> WebTeleNo { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Branch>(entity =>
        {
            entity.HasKey(e => e.RecSerialNo).HasName("PK__Branch__FB76070253076E7A");

            entity.HasIndex(e => e.BranchID, "Index_01").IsUnique();

            entity.HasIndex(e => e.Name, "Index_02");

            entity.HasIndex(e => e.GroupID, "Index_97");

            entity.HasIndex(e => e.RecordControlDateTime, "Index_98");

            entity.HasIndex(e => e.RecordControl, "Index_99");

            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.BankID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.BranchID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.CityCode)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false);
            entity.Property(e => e.EastLongitude).HasMaxLength(50);
            entity.Property(e => e.GroupID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.NorthLatitude).HasMaxLength(50);
            entity.Property(e => e.RFU).HasMaxLength(10);
            entity.Property(e => e.RecordControlDateTime).HasColumnType("datetime");
            entity.Property(e => e.ServiceEndTime).HasMaxLength(100);
            entity.Property(e => e.ServiceStartTime).HasMaxLength(100);
            entity.Property(e => e.TeleNo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ZoneCode)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false);
        });

        modelBuilder.Entity<WebTeleNo>(entity =>
        {
            entity.HasKey(e => e.TeleNo).HasName("PK__WebTeleN__B6081DD0A8CE5254");

            entity.HasIndex(e => e.QRCode, "Index_01");

            entity.HasIndex(e => e.QRCodeStartTime, "Index_02");

            entity.HasIndex(e => e.IP, "Index_03");

            entity.HasIndex(e => e.CreateTime, "Index_04");

            entity.HasIndex(e => e.LastAccessTime, "Index_05");

            entity.HasIndex(e => e.RecordControlDateTime, "Index_98");

            entity.HasIndex(e => e.RecordControl, "Index_99");

            entity.Property(e => e.TeleNo)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.AccountNo)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.CreateTime).HasColumnType("datetime");
            entity.Property(e => e.IP)
                .IsRequired()
                .HasMaxLength(70)
                .IsUnicode(false);
            entity.Property(e => e.LastAccessTime).HasColumnType("datetime");
            entity.Property(e => e.LastGetCallNoTime).HasColumnType("datetime");
            entity.Property(e => e.QRCode)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.QRCodeStartTime).HasColumnType("datetime");
            entity.Property(e => e.RFU).HasMaxLength(10);
            entity.Property(e => e.RecordControlDateTime).HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}