// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPITest2.Models;

public partial class WebTeleNo
{
    public int RecordControl { get; set; }

    public DateTime RecordControlDateTime { get; set; }

    public int Enabled { get; set; }

    public DateTime? CreateTime { get; set; }

    public DateTime? LastAccessTime { get; set; }

    public string TeleNo { get; set; }

    public string AccountNo { get; set; }

    public DateTime? LastGetCallNoTime { get; set; }

    public int? TotalGetCallNo { get; set; }

    public string IP { get; set; }

    public string QRCode { get; set; }

    public DateTime? QRCodeStartTime { get; set; }

    public int? TotalForm { get; set; }

    public string RFU { get; set; }
}