// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebAPI_Test_3.Models;

public partial class DBContext : DbContext
{
    public DBContext(DbContextOptions<DBContext> options)
        : base(options)   
    {
    }

    public virtual DbSet<Bank> Bank { get; set; }

    public virtual DbSet<Branch> Branch { get; set; }

    public virtual DbSet<BranchComputer> BranchComputer { get; set; }

    public virtual DbSet<BranchDeviceStatus> BranchDeviceStatus { get; set; }

    public virtual DbSet<BranchGroup> BranchGroup { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bank>(entity =>
        {
            entity.HasKey(e => e.RecSerialNo).HasName("PK__Bank__FB760702935545CE");

            entity.HasIndex(e => e.BankID, "Index_01").IsUnique();

            entity.HasIndex(e => e.RecordControlDateTime, "Index_98");

            entity.HasIndex(e => e.RecordControl, "Index_99");

            entity.Property(e => e.BankID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Name).HasMaxLength(50);
            entity.Property(e => e.ProductName).HasMaxLength(50);
            entity.Property(e => e.RFU).HasMaxLength(10);
            entity.Property(e => e.RecordControlDateTime).HasColumnType("datetime");
        });

        modelBuilder.Entity<Branch>(entity =>
        {
            entity.HasKey(e => e.RecSerialNo).HasName("PK__Branch__FB76070253076E7A");

            entity.HasIndex(e => e.BranchID, "Index_01").IsUnique();

            entity.HasIndex(e => e.Name, "Index_02");

            entity.HasIndex(e => e.GroupID, "Index_97");

            entity.HasIndex(e => e.RecordControlDateTime, "Index_98");

            entity.HasIndex(e => e.RecordControl, "Index_99");

            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.BankID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.BranchID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.CityCode)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false);
            entity.Property(e => e.EastLongitude).HasMaxLength(50);
            entity.Property(e => e.GroupID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.NorthLatitude).HasMaxLength(50);
            entity.Property(e => e.RFU).HasMaxLength(10);
            entity.Property(e => e.RecordControlDateTime).HasColumnType("datetime");
            entity.Property(e => e.ServiceEndTime).HasMaxLength(100);
            entity.Property(e => e.ServiceStartTime).HasMaxLength(100);
            entity.Property(e => e.TeleNo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ZoneCode)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false);
        });

        modelBuilder.Entity<BranchComputer>(entity =>
        {
            entity.HasKey(e => e.RecSerialNo).HasName("PK__BranchCo__FB7607024C9F9827");

            entity.HasIndex(e => e.ComputerID, "Index_01").IsUnique();

            entity.Property(e => e.BankID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.BranchGroupID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.BranchID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.CPU)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.ComputerID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.ComputerIP)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.ComputerName)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.ComputerType)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.Disk)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.MacAddress)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.OS)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.PlayListStatus)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.PlayListTime).HasColumnType("datetime");
            entity.Property(e => e.PlayListVersion)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.ProgramStatus)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.ProgramTime).HasColumnType("datetime");
            entity.Property(e => e.ProgramVersion)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.RFU).HasMaxLength(20);
            entity.Property(e => e.RecordControlDateTime).HasColumnType("datetime");
            entity.Property(e => e.RemainMemory)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.ScreenID)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.TemplateNo)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<BranchDeviceStatus>(entity =>
        {
            entity.HasKey(e => e.RecSerialNo).HasName("PK__BranchDe__FB760702B535C4E8");

            entity.HasIndex(e => new { e.BranchID, e.DeviceID, e.ComputerID }, "Index_01").IsUnique();

            entity.HasIndex(e => e.RecordControlDateTime, "Index_98");

            entity.HasIndex(e => e.RecordControl, "Index_99");

            entity.Property(e => e.BankID)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.BranchID)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CPU).HasColumnType("decimal(18, 5)");
            entity.Property(e => e.ComputerID)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.DeviceID)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Disk).HasColumnType("decimal(18, 5)");
            entity.Property(e => e.HeartBeat).HasColumnType("decimal(18, 5)");
            entity.Property(e => e.LastCloseDateTime).HasColumnType("datetime");
            entity.Property(e => e.LastOpenDateTime).HasColumnType("datetime");
            entity.Property(e => e.Memory).HasColumnType("decimal(18, 5)");
            entity.Property(e => e.RFU).HasMaxLength(20);
            entity.Property(e => e.RecordControlDateTime).HasColumnType("datetime");
        });

        modelBuilder.Entity<BranchGroup>(entity =>
        {
            entity.HasKey(e => e.RecSerialNo).HasName("PK__BranchGr__FB760702F04635FC");

            entity.HasIndex(e => e.GroupID, "Index_01").IsUnique();

            entity.HasIndex(e => e.Name, "Index_02").IsUnique();

            entity.HasIndex(e => e.RecordControlDateTime, "Index_98");

            entity.HasIndex(e => e.RecordControl, "Index_99");

            entity.Property(e => e.BankID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.GroupID)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Name).HasMaxLength(50);
            entity.Property(e => e.RFU).HasMaxLength(10);
            entity.Property(e => e.RecordControlDateTime).HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}