// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPITest1.Models;

public partial class BranchComputer
{
    public int RecordControl { get; set; }

    public DateTime RecordControlDateTime { get; set; }

    public int Enabled { get; set; }

    public long RecSerialNo { get; set; }

    public string BankId { get; set; }

    public string BranchGroupId { get; set; }

    public string BranchId { get; set; }

    public string ComputerId { get; set; }

    public string ComputerName { get; set; }

    public string ComputerIp { get; set; }

    public string ComputerType { get; set; }

    public string MacAddress { get; set; }

    public string Cpu { get; set; }

    public string Disk { get; set; }

    public string RemainMemory { get; set; }

    public string Os { get; set; }

    public string TemplateNo { get; set; }

    public string PlayListVersion { get; set; }

    public string PlayListStatus { get; set; }

    public DateTime? PlayListTime { get; set; }

    public string ScreenId { get; set; }

    public string ProgramVersion { get; set; }

    public string ProgramStatus { get; set; }

    public DateTime? ProgramTime { get; set; }

    public string Rfu { get; set; }
}