// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPITest1.Models;

public partial class Branch
{
    public int RecordControl { get; set; }

    public DateTime RecordControlDateTime { get; set; }

    public int Enabled { get; set; }

    public long RecSerialNo { get; set; }

    public string BankId { get; set; }

    public string BranchId { get; set; }

    public string Name { get; set; }

    public string GroupId { get; set; }

    public string CityCode { get; set; }

    public string ZoneCode { get; set; }

    public string Address { get; set; }

    public string TeleNo { get; set; }

    public string ServiceStartTime { get; set; }

    public string ServiceEndTime { get; set; }

    public string EastLongitude { get; set; }

    public string NorthLatitude { get; set; }

    public string Rfu { get; set; }
}