// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPITest1.Models;

public partial class ChangeCustIDTeleNo
{
    public int RecordControl { get; set; }

    public DateTime RecordControlDateTime { get; set; }

    public int Enabled { get; set; }

    public DateTime CreateTime { get; set; }

    public long RecSerialNo { get; set; }

    public string CustID { get; set; }

    public string OldTeleNo { get; set; }

    public string NewTeleNo { get; set; }

    public int Process { get; set; }

    public int Exist { get; set; }

    public int Result { get; set; }

    public string RFU { get; set; }
}