// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPITest1.Models;

public partial class CommonForexTransaction
{
    public int RecordControl { get; set; }

    public DateTime RecordControlDateTime { get; set; }

    public DateTime? CreateTime { get; set; }

    public DateTime? LastAccessTime { get; set; }

    public int Enabled { get; set; }

    public long RecSerialNo { get; set; }

    public string TeleNo { get; set; }

    public int FormOrder { get; set; }

    public string CustName { get; set; }

    public string CustEngName { get; set; }

    public string CustID { get; set; }

    public string PassportCountry { get; set; }

    public string Birthday { get; set; }

    public string IssueDate { get; set; }

    public string ExpireDate { get; set; }

    public string BenefAccNo { get; set; }

    public string BenefName { get; set; }

    public string BenefAddr { get; set; }

    public string BenefTele { get; set; }

    public string BenefCountry { get; set; }

    public string BenefSWCode { get; set; }

    public string BenefBankName { get; set; }

    public string BenefBankCode { get; set; }

    public string BenefBankInfo { get; set; }

    public string BenefBankAddr { get; set; }

    public string InterMedSWCode { get; set; }

    public int? ImportTimes { get; set; }

    public string Note { get; set; }

    public string RFU { get; set; }
}