// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPITest1.Models;

public partial class CommonTWTransaction
{
    public int RecordControl { get; set; }

    public DateTime RecordControlDateTime { get; set; }

    public DateTime CreateTime { get; set; }

    public DateTime LastAccessTime { get; set; }

    public int Enabled { get; set; }

    public long RecSerialNo { get; set; }

    public string TeleNo { get; set; }

    public int FormOrder { get; set; }

    public string Bank { get; set; }

    public string Branch { get; set; }

    public string RAccNo { get; set; }

    public string RName { get; set; }

    public string InName { get; set; }

    public string TID { get; set; }

    public string PTele { get; set; }

    public string TSelf { get; set; }

    public string PName { get; set; }

    public string PID { get; set; }

    public int ImportTimes { get; set; }

    public string Note { get; set; }

    public string RFU { get; set; }
}