// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPITest1.Models;

public partial class SystemParameter
{
    public int RecordControl { get; set; }

    public DateTime RecordControlDateTime { get; set; }

    public int Enabled { get; set; }

    public long RecSerialNo { get; set; }

    public string FuncParamID { get; set; }

    public string ParameterCode { get; set; }

    public string ParameterName { get; set; }

    public string ParameterValue { get; set; }

    public string RFU { get; set; }
}