// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPITest1.Models;

public partial class TaiwanBankBranch
{
    public int RecordControl { get; set; }

    public DateTime RecordControlDateTime { get; set; }

    public int Enabled { get; set; }

    public long RecSerialNo { get; set; }

    public string BankID { get; set; }

    public string BranchID { get; set; }

    public string BranchName { get; set; }

    public string RFU { get; set; }
}