// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPITest1.Models;

public partial class WorkingDay
{
    public DateTime Wdate { get; set; }

    public string Wdate1 { get; set; }

    public string Status { get; set; }

    public string BatchDate { get; set; }

    public DateTime? VbatchDate { get; set; }
}