// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPITest1.Models;

public partial class WorkingDay
{
    public DateTime WDate { get; set; }

    public string WDate1 { get; set; }

    public string Status { get; set; }

    public string batch_date { get; set; }

    public DateTime? Vbatch_date { get; set; }
}