// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_Test_5.Models;

public partial class BranchComputer
{
    public int RecordControl { get; set; }

    public DateTime RecordControlDateTime { get; set; }

    public int Enabled { get; set; }

    public long RecSerialNo { get; set; }

    public string BankID { get; set; }

    public string BranchGroupID { get; set; }

    public string BranchID { get; set; }

    public string ComputerID { get; set; }

    public string ComputerName { get; set; }

    public string ComputerIP { get; set; }

    public string ComputerType { get; set; }

    public string MacAddress { get; set; }

    public string CPU { get; set; }

    public string Disk { get; set; }

    public string RemainMemory { get; set; }

    public string OS { get; set; }

    public string TemplateNo { get; set; }

    public string PlayListVersion { get; set; }

    public string PlayListStatus { get; set; }

    public DateTime? PlayListTime { get; set; }

    public string ScreenID { get; set; }

    public string ProgramVersion { get; set; }

    public string ProgramStatus { get; set; }

    public DateTime? ProgramTime { get; set; }

    public string RFU { get; set; }
}