// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_Test_5.Models;

public partial class BranchGroup
{
    public int RecordControl { get; set; }

    public DateTime RecordControlDateTime { get; set; }

    public int Enabled { get; set; }

    public long RecSerialNo { get; set; }

    public string BankID { get; set; }

    public string GroupID { get; set; }

    public string Name { get; set; }

    public string RFU { get; set; }
}