// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPITest6.Models;

public partial class BranchDeviceStatus
{
    public int RecordControl { get; set; }

    public DateTime RecordControlDateTime { get; set; }

    public int Enabled { get; set; }

    public long RecSerialNo { get; set; }

    public string BankID { get; set; }

    public string BranchID { get; set; }

    public string DeviceID { get; set; }

    public string ComputerID { get; set; }

    public decimal Disk { get; set; }

    public decimal Memory { get; set; }

    public decimal CPU { get; set; }

    public decimal HeartBeat { get; set; }

    public DateTime LastOpenDateTime { get; set; }

    public DateTime LastCloseDateTime { get; set; }

    public string RFU { get; set; }
}