// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPITest6.Models;

public partial class CommonAccount
{
    public int RecordControl { get; set; }

    public DateTime RecordControlDateTime { get; set; }

    public int Enabled { get; set; }

    public DateTime? CreateTime { get; set; }

    public DateTime? LastAccessTime { get; set; }

    public string TeleNo { get; set; }

    public string AccountType { get; set; }

    public string AccountNo { get; set; }

    public string RFU { get; set; }
}