// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebAPITest6.Models;

public partial class DBContext : DbContext
{
    public DBContext(DbContextOptions<DBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Bank> Bank { get; set; }

    public virtual DbSet<Branch> Branch { get; set; }

    public virtual DbSet<BranchComputer> BranchComputer { get; set; }

    public virtual DbSet<BranchDeviceStatus> BranchDeviceStatus { get; set; }

    public virtual DbSet<BranchGroup> BranchGroup { get; set; }

    public virtual DbSet<ChangeCustIDTeleNo> ChangeCustIDTeleNo { get; set; }

    public virtual DbSet<CommonAccount> CommonAccount { get; set; }

    public virtual DbSet<CommonForexTransaction> CommonForexTransaction { get; set; }

    public virtual DbSet<CommonTWTransaction> CommonTWTransaction { get; set; }

    public virtual DbSet<QRCodes> QRCodes { get; set; }

    public virtual DbSet<SystemParameter> SystemParameter { get; set; }

    public virtual DbSet<TaiwanBank> TaiwanBank { get; set; }

    public virtual DbSet<TaiwanBankBranch> TaiwanBankBranch { get; set; }

    public virtual DbSet<TaiwanCity> TaiwanCity { get; set; }

    public virtual DbSet<TaiwanZone> TaiwanZone { get; set; }

    public virtual DbSet<WebTeleNo> WebTeleNo { get; set; }

    public virtual DbSet<WorkingDay> WorkingDay { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bank>(entity =>
        {
            entity.HasKey(e => e.RecSerialNo).HasName("PK__Bank__FB760702935545CE");

            entity.HasIndex(e => e.BankID, "Index_01").IsUnique();

            entity.HasIndex(e => e.RecordControlDateTime, "Index_98");

            entity.HasIndex(e => e.RecordControl, "Index_99");

            entity.Property(e => e.BankID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Name).HasMaxLength(50);
            entity.Property(e => e.ProductName).HasMaxLength(50);
            entity.Property(e => e.RFU).HasMaxLength(10);
            entity.Property(e => e.RecordControlDateTime).HasColumnType("datetime");
        });

        modelBuilder.Entity<Branch>(entity =>
        {
            entity.HasKey(e => e.RecSerialNo).HasName("PK__Branch__FB76070253076E7A");

            entity.HasIndex(e => e.BranchID, "Index_01").IsUnique();

            entity.HasIndex(e => e.Name, "Index_02");

            entity.HasIndex(e => e.GroupID, "Index_97");

            entity.HasIndex(e => e.RecordControlDateTime, "Index_98");

            entity.HasIndex(e => e.RecordControl, "Index_99");

            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.BankID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.BranchID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.CityCode)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false);
            entity.Property(e => e.EastLongitude).HasMaxLength(50);
            entity.Property(e => e.GroupID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.NorthLatitude).HasMaxLength(50);
            entity.Property(e => e.RFU).HasMaxLength(10);
            entity.Property(e => e.RecordControlDateTime).HasColumnType("datetime");
            entity.Property(e => e.ServiceEndTime).HasMaxLength(100);
            entity.Property(e => e.ServiceStartTime).HasMaxLength(100);
            entity.Property(e => e.TeleNo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ZoneCode)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false);
        });

        modelBuilder.Entity<BranchComputer>(entity =>
        {
            entity.HasKey(e => e.RecSerialNo).HasName("PK__BranchCo__FB7607024C9F9827");

            entity.HasIndex(e => e.ComputerID, "Index_01").IsUnique();

            entity.Property(e => e.BankID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.BranchGroupID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.BranchID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.CPU)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.ComputerID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.ComputerIP)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.ComputerName)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.ComputerType)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.Disk)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.MacAddress)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.OS)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.PlayListStatus)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.PlayListTime).HasColumnType("datetime");
            entity.Property(e => e.PlayListVersion)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.ProgramStatus)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.ProgramTime).HasColumnType("datetime");
            entity.Property(e => e.ProgramVersion)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.RFU).HasMaxLength(20);
            entity.Property(e => e.RecordControlDateTime).HasColumnType("datetime");
            entity.Property(e => e.RemainMemory)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.ScreenID)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.TemplateNo)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<BranchDeviceStatus>(entity =>
        {
            entity.HasKey(e => e.RecSerialNo).HasName("PK__BranchDe__FB760702B535C4E8");

            entity.HasIndex(e => new { e.BranchID, e.DeviceID, e.ComputerID }, "Index_01").IsUnique();

            entity.HasIndex(e => e.RecordControlDateTime, "Index_98");

            entity.HasIndex(e => e.RecordControl, "Index_99");

            entity.Property(e => e.BankID)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.BranchID)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CPU).HasColumnType("decimal(18, 5)");
            entity.Property(e => e.ComputerID)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.DeviceID)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Disk).HasColumnType("decimal(18, 5)");
            entity.Property(e => e.HeartBeat).HasColumnType("decimal(18, 5)");
            entity.Property(e => e.LastCloseDateTime).HasColumnType("datetime");
            entity.Property(e => e.LastOpenDateTime).HasColumnType("datetime");
            entity.Property(e => e.Memory).HasColumnType("decimal(18, 5)");
            entity.Property(e => e.RFU).HasMaxLength(20);
            entity.Property(e => e.RecordControlDateTime).HasColumnType("datetime");
        });

        modelBuilder.Entity<BranchGroup>(entity =>
        {
            entity.HasKey(e => e.RecSerialNo).HasName("PK__BranchGr__FB760702F04635FC");

            entity.HasIndex(e => e.GroupID, "Index_01").IsUnique();

            entity.HasIndex(e => e.Name, "Index_02").IsUnique();

            entity.HasIndex(e => e.RecordControlDateTime, "Index_98");

            entity.HasIndex(e => e.RecordControl, "Index_99");

            entity.Property(e => e.BankID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.GroupID)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Name).HasMaxLength(50);
            entity.Property(e => e.RFU).HasMaxLength(10);
            entity.Property(e => e.RecordControlDateTime).HasColumnType("datetime");
        });

        modelBuilder.Entity<ChangeCustIDTeleNo>(entity =>
        {
            entity.HasKey(e => e.RecSerialNo).HasName("PK__ChangeCu__FB760702582C6695");

            entity.HasIndex(e => e.CustID, "Index_01");

            entity.HasIndex(e => e.OldTeleNo, "Index_02");

            entity.HasIndex(e => e.NewTeleNo, "Index_03");

            entity.HasIndex(e => e.Result, "Index_04");

            entity.HasIndex(e => new { e.CustID, e.CreateTime }, "Index_05");

            entity.HasIndex(e => e.RecordControlDateTime, "Index_98");

            entity.HasIndex(e => e.RecordControl, "Index_99");

            entity.Property(e => e.CreateTime).HasColumnType("datetime");
            entity.Property(e => e.CustID)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.NewTeleNo)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.OldTeleNo)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.RFU).HasMaxLength(10);
            entity.Property(e => e.RecordControlDateTime).HasColumnType("datetime");
        });

        modelBuilder.Entity<CommonAccount>(entity =>
        {
            entity.HasKey(e => e.TeleNo).HasName("PK__CommonAc__B6081DD0E7B6063F");

            entity.HasIndex(e => e.TeleNo, "Index_01").IsUnique();

            entity.HasIndex(e => e.AccountType, "Index_02");

            entity.HasIndex(e => e.AccountNo, "Index_03");

            entity.HasIndex(e => e.CreateTime, "Index_04");

            entity.HasIndex(e => e.RecordControlDateTime, "Index_98");

            entity.HasIndex(e => e.RecordControl, "Index_99");

            entity.Property(e => e.TeleNo)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.AccountNo)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.AccountType)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.CreateTime).HasColumnType("datetime");
            entity.Property(e => e.LastAccessTime).HasColumnType("datetime");
            entity.Property(e => e.RFU).HasMaxLength(50);
            entity.Property(e => e.RecordControlDateTime).HasColumnType("datetime");
        });

        modelBuilder.Entity<CommonForexTransaction>(entity =>
        {
            entity.HasKey(e => e.RecSerialNo).HasName("PK__CommonFo__FB7607023BB27AE7");

            entity.HasIndex(e => new { e.TeleNo, e.CreateTime, e.CustID }, "Index_01").IsUnique();

            entity.HasIndex(e => new { e.TeleNo, e.FormOrder }, "Index_02").IsUnique();

            entity.HasIndex(e => e.TeleNo, "Index_03");

            entity.HasIndex(e => e.RecordControlDateTime, "Index_98");

            entity.HasIndex(e => e.RecordControl, "Index_99");

            entity.Property(e => e.BenefAccNo)
                .IsRequired()
                .HasMaxLength(34)
                .IsUnicode(false);
            entity.Property(e => e.BenefAddr)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.BenefBankAddr)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.BenefBankCode)
                .IsRequired()
                .HasMaxLength(14)
                .IsUnicode(false);
            entity.Property(e => e.BenefBankInfo)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.BenefBankName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.BenefCountry)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.BenefName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.BenefSWCode)
                .IsRequired()
                .HasMaxLength(11)
                .IsUnicode(false);
            entity.Property(e => e.BenefTele)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Birthday)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.CreateTime).HasColumnType("datetime");
            entity.Property(e => e.CustEngName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CustID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.CustName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ExpireDate)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.InterMedSWCode)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.IssueDate)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.LastAccessTime).HasColumnType("datetime");
            entity.Property(e => e.Note)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.PassportCountry)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.RFU).HasMaxLength(20);
            entity.Property(e => e.RecordControlDateTime).HasColumnType("datetime");
            entity.Property(e => e.TeleNo)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<CommonTWTransaction>(entity =>
        {
            entity.HasKey(e => e.RecSerialNo).HasName("PK__CommonTW__FB760702A44ADA35");

            entity.HasIndex(e => new { e.TeleNo, e.CreateTime, e.RAccNo }, "Index_01").IsUnique();

            entity.HasIndex(e => new { e.TeleNo, e.FormOrder }, "Index_02").IsUnique();

            entity.HasIndex(e => e.TeleNo, "Index_03");

            entity.HasIndex(e => e.RecordControlDateTime, "Index_98");

            entity.HasIndex(e => e.RecordControl, "Index_99");

            entity.Property(e => e.Bank)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false);
            entity.Property(e => e.Branch)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false);
            entity.Property(e => e.CreateTime).HasColumnType("datetime");
            entity.Property(e => e.InName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.LastAccessTime).HasColumnType("datetime");
            entity.Property(e => e.Note)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.PID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.PName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PTele)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.RAccNo)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.RFU).HasMaxLength(20);
            entity.Property(e => e.RName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RecordControlDateTime).HasColumnType("datetime");
            entity.Property(e => e.TID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.TSelf)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.TeleNo)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<QRCodes>(entity =>
        {
            entity.HasKey(e => e.RecSerialNo).HasName("PK__QRCode__FB760702CEEDA011");

            entity.HasIndex(e => new { e.TeleNo, e.QRCode }, "Index_01").IsUnique();

            entity.HasIndex(e => new { e.KeyNo, e.QRCode }, "Index_02").IsUnique();

            entity.HasIndex(e => new { e.KeyNo, e.QRCodeStratDate }, "Index_03");

            entity.HasIndex(e => e.QRCodeStratDate, "Index_04");

            entity.HasIndex(e => e.IP, "Index_05");

            entity.HasIndex(e => e.ServiceStatus, "Index_06");

            entity.HasIndex(e => e.GetNoRecSerialNo, "Index_07");

            entity.HasIndex(e => e.RecordControlDateTime, "Index_98");

            entity.HasIndex(e => e.RecordControl, "Index_99");

            entity.Property(e => e.CreateTime).HasColumnType("datetime");
            entity.Property(e => e.IP)
                .IsRequired()
                .HasMaxLength(70)
                .IsUnicode(false);
            entity.Property(e => e.KeyNo)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.LastAccessTime).HasColumnType("datetime");
            entity.Property(e => e.QRCode)
                .IsRequired()
                .HasMaxLength(18)
                .IsUnicode(false)
                .HasColumnName("QRCode");
            entity.Property(e => e.QRCodeEndDate)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.QRCodeStratDate)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.RFU).HasMaxLength(20);
            entity.Property(e => e.RecordControlDateTime).HasColumnType("datetime");
            entity.Property(e => e.ServiceStatus)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.TeleNo)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<SystemParameter>(entity =>
        {
            entity.HasKey(e => e.RecSerialNo).HasName("PK__SystemPa__FB760702FB8AF3CF");

            entity.HasIndex(e => new { e.FuncParamID, e.ParameterCode }, "Index_01").IsUnique();

            entity.HasIndex(e => e.RecordControlDateTime, "Index_98");

            entity.HasIndex(e => e.RecordControl, "Index_99");

            entity.Property(e => e.FuncParamID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.ParameterCode)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.ParameterName)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.ParameterValue)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RFU).HasMaxLength(20);
            entity.Property(e => e.RecordControlDateTime).HasColumnType("datetime");
        });

        modelBuilder.Entity<TaiwanBank>(entity =>
        {
            entity.HasKey(e => e.RecSerialNo);

            entity.HasIndex(e => e.BankID, "Index_01").IsUnique();

            entity.Property(e => e.RecSerialNo).ValueGeneratedNever();
            entity.Property(e => e.BankID)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false);
            entity.Property(e => e.BankName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RFU).HasMaxLength(50);
        });

        modelBuilder.Entity<TaiwanBankBranch>(entity =>
        {
            entity.HasKey(e => e.RecSerialNo).HasName("PK__TaiwanBa__FB76070267118A4C");

            entity.HasIndex(e => new { e.BankID, e.BranchID }, "Index_01").IsUnique();

            entity.HasIndex(e => e.RecordControlDateTime, "Index_98");

            entity.HasIndex(e => e.RecordControl, "Index_99");

            entity.Property(e => e.BankID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.BranchID)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.BranchName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RFU).HasMaxLength(20);
            entity.Property(e => e.RecordControlDateTime).HasColumnType("datetime");
        });

        modelBuilder.Entity<TaiwanCity>(entity =>
        {
            entity.HasKey(e => e.RecSerialNo).HasName("PK__TaiwanCi__FB76070288CDD5DA");

            entity.Property(e => e.CityCode)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false);
            entity.Property(e => e.CityName)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.RFU)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.RecordControlDateTime).HasColumnType("datetime");
            entity.Property(e => e.TelArea)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TaiwanZone>(entity =>
        {
            entity.HasKey(e => e.RecSerialNo).HasName("PK__TaiwanZo__FB760702757D4D27");

            entity.Property(e => e.CityCode)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false);
            entity.Property(e => e.PostCode)
                .IsRequired()
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.RFU).HasMaxLength(20);
            entity.Property(e => e.RecordControlDateTime).HasColumnType("datetime");
            entity.Property(e => e.ZoneCode)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false);
            entity.Property(e => e.ZoneName)
                .IsRequired()
                .HasMaxLength(10);
        });

        modelBuilder.Entity<WebTeleNo>(entity =>
        {
            entity.HasKey(e => e.TeleNo).HasName("PK__WebTeleN__B6081DD0A8CE5254");

            entity.HasIndex(e => e.QRCode, "Index_01");

            entity.HasIndex(e => e.QRCodeStartTime, "Index_02");

            entity.HasIndex(e => e.IP, "Index_03");

            entity.HasIndex(e => e.CreateTime, "Index_04");

            entity.HasIndex(e => e.LastAccessTime, "Index_05");

            entity.HasIndex(e => e.RecordControlDateTime, "Index_98");

            entity.HasIndex(e => e.RecordControl, "Index_99");

            entity.Property(e => e.TeleNo)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.AccountNo)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.CreateTime).HasColumnType("datetime");
            entity.Property(e => e.CustID)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.IP)
                .IsRequired()
                .HasMaxLength(70)
                .IsUnicode(false);
            entity.Property(e => e.LastAccessTime).HasColumnType("datetime");
            entity.Property(e => e.LastGetCallNoTime).HasColumnType("datetime");
            entity.Property(e => e.QRCode)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.QRCodeStartTime).HasColumnType("datetime");
            entity.Property(e => e.RFU).HasMaxLength(10);
            entity.Property(e => e.RecordControlDateTime).HasColumnType("datetime");
        });

        modelBuilder.Entity<WorkingDay>(entity =>
        {
            entity.HasNoKey();

            entity.HasIndex(e => e.WDate, "Index_01").IsUnique();

            entity.Property(e => e.Status)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.Vbatch_date).HasColumnType("datetime");
            entity.Property(e => e.WDate).HasColumnType("datetime");
            entity.Property(e => e.WDate1)
                .HasMaxLength(8)
                .IsUnicode(false);
            entity.Property(e => e.batch_date)
                .HasMaxLength(1)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}