// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPITest6.Models;

public partial class QRCode
{
    public int RecordControl { get; set; }

    public DateTime RecordControlDateTime { get; set; }

    public int Enabled { get; set; }

    public DateTime? CreateTime { get; set; }

    public DateTime? LastAccessTime { get; set; }

    public long RecSerialNo { get; set; }

    public string TeleNo { get; set; }

    public string KeyNo { get; set; }

    public string QRCode1 { get; set; }

    public string QRCodeStratDate { get; set; }

    public string QRCodeEndDate { get; set; }

    public int TotalForm { get; set; }

    public string IP { get; set; }

    public string ServiceStatus { get; set; }

    public long GetNoRecSerialNo { get; set; }

    public string RFU { get; set; }
}