// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPITest6.Models;

public partial class TaiwanZone
{
    public int RecordControl { get; set; }

    public DateTime RecordControlDateTime { get; set; }

    public int Enabled { get; set; }

    public long RecSerialNo { get; set; }

    public string CityCode { get; set; }

    public string ZoneCode { get; set; }

    public string ZoneName { get; set; }

    public string PostCode { get; set; }

    public string RFU { get; set; }
}