// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPITest6.Models;

public partial class TaiwanBank
{
    public int RecordControl { get; set; }

    public DateTime RecordControlDateTime { get; set; }

    public int Enabled { get; set; }

    public int RecSerialNo { get; set; }

    public string BankID { get; set; }

    public string BankName { get; set; }

    public string RFU { get; set; }
}